# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Oct  3 20:54:26 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(497, 462)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.hboxlayout = QtGui.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.gardenView = GardenView(self.centralwidget)
        self.gardenView.setLineWidth(0)
        self.gardenView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gardenView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.gardenView.setAlignment(QtCore.Qt.AlignCenter)
        self.gardenView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.gardenView.setDragMode(QtGui.QGraphicsView.NoDrag)
        self.gardenView.setCacheMode(QtGui.QGraphicsView.CacheNone)
        self.gardenView.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.gardenView.setResizeAnchor(QtGui.QGraphicsView.NoAnchor)
        self.gardenView.setViewportUpdateMode(QtGui.QGraphicsView.SmartViewportUpdate)
        self.gardenView.setObjectName(_fromUtf8("gardenView"))
        self.hboxlayout.addWidget(self.gardenView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_New = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addFile(_fromUtf8(":/images/new.png"))
        self.action_New.setIcon(icon)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_Open = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addFile(_fromUtf8(":/images/open.png"))
        self.action_Open.setIcon(icon1)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Save = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addFile(_fromUtf8(":/images/save.png"))
        self.action_Save.setIcon(icon2)
        self.action_Save.setObjectName(_fromUtf8("action_Save"))
        self.action_Print = QtGui.QAction(MainWindow)
        self.action_Print.setObjectName(_fromUtf8("action_Print"))
        self.action_Select_All = QtGui.QAction(MainWindow)
        self.action_Select_All.setObjectName(_fromUtf8("action_Select_All"))
        self.action_Select_None = QtGui.QAction(MainWindow)
        self.action_Select_None.setObjectName(_fromUtf8("action_Select_None"))
        self.action_Delete = QtGui.QAction(MainWindow)
        self.action_Delete.setObjectName(_fromUtf8("action_Delete"))
        self.action_Undo = QtGui.QAction(MainWindow)
        self.action_Undo.setObjectName(_fromUtf8("action_Undo"))
        self.action_Redo = QtGui.QAction(MainWindow)
        self.action_Redo.setObjectName(_fromUtf8("action_Redo"))
        self.action_Save_As = QtGui.QAction(MainWindow)
        self.action_Save_As.setObjectName(_fromUtf8("action_Save_As"))
        self.action_Place_Plant = QtGui.QAction(MainWindow)
        self.action_Place_Plant.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addFile(_fromUtf8(":/plants/tomato.svg"))
        self.action_Place_Plant.setIcon(icon3)
        self.action_Place_Plant.setObjectName(_fromUtf8("action_Place_Plant"))
        self.action_Rectangular_Selection = QtGui.QAction(MainWindow)
        self.action_Rectangular_Selection.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addFile(_fromUtf8(":/images/select-rectangular.png"))
        self.action_Rectangular_Selection.setIcon(icon4)
        self.action_Rectangular_Selection.setObjectName(_fromUtf8("action_Rectangular_Selection"))
        self.action_Plant_Row = QtGui.QAction(MainWindow)
        self.action_Plant_Row.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addFile(_fromUtf8(":/images/plantrow.svg"))
        self.action_Plant_Row.setIcon(icon5)
        self.action_Plant_Row.setObjectName(_fromUtf8("action_Plant_Row"))
        self.action_Plant_Bed = QtGui.QAction(MainWindow)
        self.action_Plant_Bed.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addFile(_fromUtf8(":/images/plantbed.svg"))
        self.action_Plant_Bed.setIcon(icon6)
        self.action_Plant_Bed.setObjectName(_fromUtf8("action_Plant_Bed"))
        self.action_Ruler = QtGui.QAction(MainWindow)
        self.action_Ruler.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addFile(_fromUtf8(":/images/ruler.svg"))
        self.action_Ruler.setIcon(icon7)
        self.action_Ruler.setObjectName(_fromUtf8("action_Ruler"))
        self.action_Garden_Properties = QtGui.QAction(MainWindow)
        self.action_Garden_Properties.setObjectName(_fromUtf8("action_Garden_Properties"))
        self.action_Show_Row_Spacing = QtGui.QAction(MainWindow)
        self.action_Show_Row_Spacing.setCheckable(True)
        self.action_Show_Row_Spacing.setChecked(False)
        self.action_Show_Row_Spacing.setEnabled(False)
        self.action_Show_Row_Spacing.setObjectName(_fromUtf8("action_Show_Row_Spacing"))
        self.action_Show_Plant_Spacing = QtGui.QAction(MainWindow)
        self.action_Show_Plant_Spacing.setCheckable(True)
        self.action_Show_Plant_Spacing.setChecked(True)
        self.action_Show_Plant_Spacing.setObjectName(_fromUtf8("action_Show_Plant_Spacing"))
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Delete)
        self.menu_Edit.addAction(self.action_Select_All)
        self.menu_Edit.addAction(self.action_Select_None)
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_Save_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Print)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Garden_Properties)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_View.addAction(self.action_Show_Plant_Spacing)
        self.menu_View.addAction(self.action_Show_Row_Spacing)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.toolBar.addAction(self.action_New)
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addAction(self.action_Save)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Garden Freely", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setText(QtGui.QApplication.translate("MainWindow", "&New...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Print.setText(QtGui.QApplication.translate("MainWindow", "&Print", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Print.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Select_All.setText(QtGui.QApplication.translate("MainWindow", "Select &All", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Select_All.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Select_None.setText(QtGui.QApplication.translate("MainWindow", "Select &None", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Select_None.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+A", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Delete.setText(QtGui.QApplication.translate("MainWindow", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Delete.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Undo.setText(QtGui.QApplication.translate("MainWindow", "&Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Undo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Redo.setText(QtGui.QApplication.translate("MainWindow", "&Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Redo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save_As.setText(QtGui.QApplication.translate("MainWindow", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Place_Plant.setText(QtGui.QApplication.translate("MainWindow", "Place Plant", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Place_Plant.setShortcut(QtGui.QApplication.translate("MainWindow", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Rectangular_Selection.setText(QtGui.QApplication.translate("MainWindow", "Rectangular Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Rectangular_Selection.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Plant_Row.setText(QtGui.QApplication.translate("MainWindow", "Plant Row", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Plant_Row.setShortcut(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Plant_Bed.setText(QtGui.QApplication.translate("MainWindow", "Plant Bed", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Plant_Bed.setShortcut(QtGui.QApplication.translate("MainWindow", "F4", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Ruler.setText(QtGui.QApplication.translate("MainWindow", "Ruler", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Ruler.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Garden_Properties.setText(QtGui.QApplication.translate("MainWindow", "&Garden Properties...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Show_Row_Spacing.setText(QtGui.QApplication.translate("MainWindow", "Show &Row Spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Show_Plant_Spacing.setText(QtGui.QApplication.translate("MainWindow", "Show &Plant Spacing", None, QtGui.QApplication.UnicodeUTF8))

from gardenview import GardenView
import gardenfreely_rc
